---
AGO: Attorney General’s Office
ALB: Arms Length Bodies
BAU: Business as Usual
BCS: British Computer Society
BEIS: Department of Business, Energy and Industrial Strategy
BIS: Department for Business, Innovation and Skills
CA: Citizens Advice
CAB: Change Advisory Board
CAF: Common Assessment Framework
CCG: Clinical Commissioning Group
CCS: Crown Commercial Service
CCW: Consumer Council for Water
CO: Cabinet Office
CPS: Crown Prosecution Service
CQC: Care Quality Commission
Cafcass: Children and Family Court Advisory and Support Service
DBS: Disclosure & Barring Service
DCLG: Department for Communities & Local Government
DCMS: Department for Digital, Culture, Media and Sport
DDAT: Digital, Data and Technology
DExEU: Department for Exiting the EU
DFID: Department for International Development
DFT: Department for Transport
DHSC: Department of Health and Social Care
DIT: Department of International Trade
DOS: Digital Outcomes and Specialists
DVLA: Driver and Vehicle Licensing Agency
DVSA: Driver & Vehicle Standards Agency
DWP: Department for Work and Pensions
Defra: Department for Environment, Food and Rural Affairs
DfE: Department for Education
ERG: Efficiency and Reform Group
FBC: Full Business Case
FCA: Financial Conduct Authority
FCO: Foreign and Commonwealth Office
FSA: Food Standards Authority
FTE: Full-time Equivalent
FoI: Freedom of Information
GDS: Government Digital Service
GLS: Government Legal Service
GMPP: Government's Major Projects Portfolio
GSI: Government Secure Intranet
HEE: Health Education England
HMCTS: Her Majesty's Courts & Tribunals Service
HMG: Her Majesty's Government
HMIC: Her Majesty's Inspectorate of Constabulary
HMRC: Her Majesty's Revenue and Customs
HMT: Her Majesty's Treasury
HO: Home Office
HRA: Health Research Authority
ICO: Information Commissioner's Office
IPA: Infrastructure and Projects Authority
IPO: Intellectual Property Office
ITHC: IT Health Check
ITIL: Information Technology Infrastructure Library
ITT: Invitation to Tender
JAC: Judicial Appointments Commission
KPI: Key Performance Indicator
LA: Local Authority
LAA: Legal Aid Agency
MHCLG: Ministry of Housing, Communities and Local Government
MISO: Management System Information Online
MVP: Minimum Viable Product
MoG: Machinery of Government
MoJ: Ministry of Justice
MoPA: Major Projects Authority
NAO: National Audit Office
NCA: National Crime Agency
NCSC: National Cyber-Security Centre
NDPB: Non-Departmental Public Body
NGO: Non-Governmental organisation
NHS: National Health Service
NHSE: NHS England
NICE: National Institute of Clinical Excellence
NIO: Northern Ireland Office
NS&I: National Savings & Investments
OBC: Outline Business Case
OBR: Office for Budget Responsibility
OGD: Other Government Departments
OKR: Objectives and Key Results
ONS: Office for National Statistics
OPG: Office of the Public Guardian
Ofcom: Office of Communications
Ofgem: Office of Gas & Electricity Markets
Ofqual: Office of Qualifications and Examinations Regulation
Ofsted: Office for Standards in Education, Children's Services and Skills
PAC: Public Accounts Committee
PASC: Public Administration Select Committee
PCT: Primary Care Trust
PHE: Public Health England
PM: Product Manager
PSN: Public Sector Network
QAR: Quality Assurance Reviews
SCS: Senior Civil Service
SFO: Serious Fraud Office
SHA: Strategic Health Authority
SIRO: Senior Information Risk Owner
SOC: Strategic Outline Case
SRO: Senior Responsible Owner
STA: Senior Technical Advisor
UKEF: UK Export Finance
VOA: Valuation Office Agency
BAS: British Antarctic Survey
AO: Arctic Office
BBB: British Business Bank
BCE: Boundary Commission for England
CBW: Community Business Weekend
CCC: The Committee on Climate Change
CoDH: Council of Deans of Health
DfT: Department for Transport
E&E: Education and Employers
ITF: Inspiring the Future
PF: Primary Futures
IG: Inspiring Governance
IFEG: Inspiring Further Education Governance
ESHT: East Sussex Healthcare NHS Trust
BAT: British Antarctic Territory
BIOT: British Indian Overseas Territory
GISF: Global Intelligence Security Forum
GLD: Government Legal Department
GOC: General Optical Council
GOsC: General Osteopathic Council
ICAI: Independent Commission for Aid Impact
LGIU: Local Government Information Unit
MoD: Ministry of Defence
AFC, AFD: Armed Forces Covenant / Day
Natcen: National Centre of Statistics (Also ScotCen)
WST: What Scotland Thinks
WUKT: What UK Thinks
GSS: Government Statistical Service
DL: Delivery Lead
UR: User Researcher
FE: Design/front end developer
BE: Developer / back end
TM: Transformation managers
SD: Service designer
SaaS: Software as a service
PaaS: Platform as a service
GPaaS: GOV.UK Platform as a Service
i18n: Internationalisation
a11y: Accessibility
l10n: localisation
SID: Statistics on International Development
FCDO: Foreign, Commonwealth & Development Office
AHRC: Arts & Humanities Research Council
BBSRC: Biotechnology and Biological Sciences Research Council
EPSRC: Engineering and Physical Sciences Research Council
ESRC: Economic and Social Research Council
IUK: Innovate UK
MRC: Medical Research Council
NERC: Natural Environment Research Council
RAEng: Royal Academy of Engineering
RE: Research England
STFC: Science and Technology Facilities
UKRI: UK Research and Innovation
IATI: International Aid Transparency Initiative
ADR: Architectural Decision Records
EOT: Employee Ownership Trust
ISPF: International Science Partnerships Fund
