name: Rebuild dictionary

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  run:
    name: Build dictionary
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Rebuild dictionary
      run: ruby lib/build_local_glossary.rb
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    - name: Create pull request with updated dictionary
      uses: peter-evans/create-pull-request@v4.2.4
      with:
        add-paths: config/acronyms.yml
        commit-message: Automatic dictionary update
        branch: update-acronyms
        delete-branch: true
        title: Update acronyms with latest definitions
        body: This is an automatically created PR to update the acronyms from the latest version of the dxw Glossary
